version: '3'
services:
  frontend:
    image: "tusan/piggy-bank-frontend:1.0"
    ports:
     - "80:80"
  backend:
    image: "tusan/piggy-bank:1.0"
    volumes:
      - ~/piggy-bank-data:/data
    ports: 
      - 8080:8080